export const NOT_LEGAL_ADVICE = 'Chips Copilot provides educational information only and is not legal advice.'

export const PRIVACY_PUBLIC_BLOCK = 'Public sharing of case materials is blocked by default to protect minors and comply with protective orders.'

export const PARENT_VERIFICATION_REQUIRED = 'This feature is only available to verified parents. Complete the verification process to access this area.'

export const AI_DISCLAIMER = 'AI-generated content is for educational purposes only. Always consult your attorney for case-specific legal guidance.'

export const DOCUMENT_REDACTION_NOTICE = 'Personal information has been automatically redacted to protect privacy. Original documents remain unchanged.'

export const FUNDRAISING_DISCLAIMER = 'Campaign funds are for legitimate case-related expenses. Misuse of funds may result in account suspension and legal action.'

export const COPILOT_GUARDRAILS = `
**Important Disclaimers:**

🔒 **Not Legal Advice**: Chips Copilot provides educational information only. This is not legal advice and should not replace consultation with a qualified attorney.

📋 **Case-Specific Guidance**: Every CPS/CHIPS case is unique. Laws and procedures vary by jurisdiction. Always consult your attorney for case-specific guidance.

🤖 **AI Limitations**: Responses are generated by AI and may contain errors. Always verify important information with legal professionals.

👨‍👩‍👧‍👦 **Parents Only**: This service is exclusively for verified parents involved in CPS/CHIPS proceedings.

📄 **Document Privacy**: Your documents are private and encrypted. They are only used to provide you with personalized guidance.
`

export const VERIFICATION_PROCESS_NOTICE = `
**Parent Verification Process:**

We verify parents through a secure process to maintain community safety and comply with court orders that may restrict access to case information.

• **Identity Verification**: Photo ID and live selfie verification
• **Case Matching**: Confirmation of your involvement in the case
• **Privacy Protection**: All verification documents are encrypted and automatically deleted after approval
• **Human Review**: Edge cases are reviewed by trained staff, not automated systems

This process protects both you and other families in our community.
`

export const DATA_RETENTION_POLICY = `
**Data Handling:**

• **Verification Documents**: Deleted within 48 hours of approval
• **Case Documents**: Encrypted and stored securely, only accessible to you
• **AI Conversations**: Encrypted and used only for your personalized assistance
• **Account Deletion**: All data permanently deleted within 30 days of account closure

Your privacy and security are our top priorities.
`

export const EMERGENCY_RESOURCES = `
**Crisis Resources:**

If you or your children are in immediate danger:
• **Call 911** for emergencies
• **National Child Abuse Hotline**: 1-800-4-A-CHILD (1-800-422-4453)
• **Crisis Text Line**: Text HOME to 741741
• **National Domestic Violence Hotline**: 1-800-799-7233

Chips Copilot is not a crisis intervention service and cannot provide emergency assistance.
`

export function getContextualDisclaimer(context: 'copilot' | 'verification' | 'vault' | 'campaign' | 'general'): string {
  switch (context) {
    case 'copilot':
      return COPILOT_GUARDRAILS
    case 'verification':
      return VERIFICATION_PROCESS_NOTICE
    case 'vault':
      return DOCUMENT_REDACTION_NOTICE + '\n\n' + PRIVACY_PUBLIC_BLOCK
    case 'campaign':
      return FUNDRAISING_DISCLAIMER + '\n\n' + PARENT_VERIFICATION_REQUIRED
    default:
      return NOT_LEGAL_ADVICE
  }
}